### ISSUE TITLE
[Wii] The Wiimote or Classic Controller don't work

### ISSUE THREAD

**Issue by Kappa971** [libretro/fbalpha2012#106]
In the Wii version of Retroarch 1.9.1, the controls (Wiimote or Classic Controller) don't work with all Final Burn Alpha 2012 cores

**Comment by Cee123** [comment]
Yeah the controls are unresponsive with this core.

They were fixed on the other cores, someone just needs to fix them on these
Related to issue:
libretro/RetroArch#11217

**Comment by Cee123** [comment]
Why did you close this? The controls still don't work even now.

**Comment by Kappa971** [comment]
> Why did you close this? The controls still don't work even now.

Because no one seems interested in solving it, plus standalone emulators work better on the Wii.
If you want to play MAME arcade games, the Wii is not the right console anyway, the system is not very powerful.

**Comment by Cee123** [comment]
You are right. They absolutely don't give a damn at all. To see that I've reported this issue four years ago and it's still the same now just shows that no one cares that these cores are broken for this particular platform. And reaching out has received no response either.
