### ISSUE TITLE
7z romset compatibility

### ISSUE THREAD

**Issue by Oggom** [libretro/fbalpha2012#22]
It looks like the common format for arcade romsets has been changed from .zip to .7z which currently renders them incompatible with RetroArch due the lack of 7z support.

With this change all different revisions of a game are now also packed in a single file making it impossible for the user to play specific revisions/hacks with RetroArch since there is no rom browser/selector like in MAME/FBA.

**Comment by barbudreadmon** [comment]
it should work with latest commit on fbalpha, feel free to backport the changes
