### ISSUE TITLE
Neo Geo CD support missing

### ISSUE THREAD

**Issue by Oggom** [libretro/fbalpha2012#28]
The standalone release of FBA supports playing Neo Geo CD games, I don't think this has been implemented in the libretro port yet.

**Comment by ultraegos** [comment]
I've found this on neoraine's page:

"Formats supported for the games

The games are all in cd format, so neoraine accepts one of these :
If you have copied the cd files somewhere, there is an ipl.txt in these files, so neoraine accepts the ipl.txt file directly, this is the most basic format (direct file access).
You can also zip the contents of the cd, and pass the zip file to neoraine. The zip file must contain an ipl.txt file in its root directory to be accepted.
Cds in a ripped form will have a cue file, an iso/bin file, and some wav or mp3 files for the audio. So the cue file is supported. Also cue/bin which include audio tracks in the bin file are supported.
For the audio files they can be in mp3, ogg, or wav files for the hysterics of the "accurate" audio ! I recommend mp3 for the tracks. So basically you should have 1 directory / game, with game files + audio files in this directory. Then when you load a game, you browse to this directory and pass the required file (zip or cue usually).
For compatibility with neocdpsp, audio files can also be placed in a neocd.mp3 directory in the game directory. So for example you would have :
Directory: Metal Slug
|- mslug.zip or mslug.cue
|+
 |-neocd.mp3
 |+ track01.mp3
  |-track02.mp3..."
 Example:
Samurai Spirits RPG 
From: 695 MB (bin/cue)
to: 96.8 MB (7z/ogg)

**Comment by hizzlekizzle** [comment]
Neo Geo CD support has been added to the non-2012 core, just FYI.
