### ISSUE TITLE
Analog control input issues

### ISSUE THREAD

**Issue by Oggom** [libretro/fbalpha2012#37]
The libretro port of FBA doesn't seem to handle analog controls properly at the moment, rendering some games unplayable.
Examples: After Burner, Rambo III and Forgotten Worlds

**Comment by justinbeaird** [comment]
Has there been any progress on this?

**Comment by Oggom** [comment]
Nop

**Comment by justinbeaird** [comment]
That sucks they work in pifba but it doesent handle as many games

**Comment by Oggom** [comment]
The inputs themselves are actually mapped out, but for some reason they don't to work as intended and nobody has been able to come up with a solution for it yet.

**Comment by fr500** [comment]
Not totally related, @justinbeaird reported this on the forum IIRC. 

Most of the supported games didn't have analog controls, so d-pad/analog mapping or fixing this should make no difference in those.

Not sure about the aforementioned exceptions

**Comment by justinbeaird** [comment]
Almost every arcade Mame game I have ever played has a joystick

**Comment by ToadKing** [comment]
Most arcade joysticks are just a stick over digital buttons.

**Comment by justinbeaird** [comment]
Well you can tell a big difference in FBA vs FBA liberto or even mame implementations. controlles are way more accurate than in fba-liberto

**Comment by fr500** [comment]
for which games?
for most arcade fighters, and shmups it should make no difference whatsoever

**Comment by barbudreadmon** [comment]
Interesting fact : bbusters, which uses analog for his light gun, works (at least on current fbalpha-libretro)

**Comment by dankcushions** [comment]
with mame (2003) it's true that most arcade games do not use true analog. there are a few exceptions that i could use for my tests: afterburner, and some light gun games that had a mounted gun (operation wolf etc). the PR for this is here: https://github.com/libretro/mame2003-libretro/pull/42

an interesting thing was that i had to change the analog scale from libretro's -32000 to +32000 range to -128 to +128 that mame wanted. it might be similar for FBA.

**Comment by barbudreadmon** [comment]
FBalpha uses -32768 to +32767 values.
Expect this issue solved this week on current fbalpha-libretro, i finally figured out what's wrong while i was rewriting some functions, i just need to figure out how to properly handle it now.

**Comment by barbudreadmon** [comment]
Fixed on current fbalpha-libretro
