### ISSUE TITLE
Update name to fbalpha2014 and romset in description to 0.2.97.30

### ISSUE THREAD

**Issue by dankcushions** [libretro/fbalpha2012#53]
This FBA is actually for romset 0.2.97.30 but the description refers to 0.2.97.24. .30 was released in 2014 so this should really be called fbalpha2014 also.

see https://github.com/libretro/fbalpha2012/commit/134c55b98b64e620a703a85061ce317fdc5816d0
and http://www.fbalpha.com/view/198/

**Comment by barbudreadmon** [comment]
I have to disagree about that, if it really was 0.2.97.30, there would be a tlcs90 directory under src/cpu/ .
I think it is 0.2.97.24 with some backports from 0.2.97.30, and i remember having missing file issues with both romset.

**Comment by dankcushions** [comment]
@barbudreadmon thanks for clarifying! i was only going off the commit

(i don't really understand how it could be .30 in that commit in 2013 if .30 was released in 2014 according to their website, but ok!)

it would be strange to me to backport only some changes, as that would make the core kinda unusable, but i don't really want to look into it :)

**Comment by barbudreadmon** [comment]
Actually, @CaptainCPS is the author of a fork of fba for ps3, and i think those changes are a backport from its fork, not from official fba.
